[workspace]
members = ["kernel"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Espyy_"]

[profile.dev]
panic = "abort"
debug = true
opt-level = 0

[profile.release]
panic = "abort"
debug = false
opt-level = 3
lto = true
codegen-units = 1
